# build a arm-eabihf binary
name: Build PyAvrOCD on linux-armeabihf
on: [workflow_dispatch]

jobs:
  build-linux32-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: arm1176
          base_image: raspios_lite:latest
          copy_artifact_path: spyavrocd
          image_additional_mb: 2048
          commands: |
            uname -a
            python3 --version
            ldd --version
            df -h /
            apt update -y
            apt install -y scons
            apt install -y python3-pip
            apt install -y python3.13-venv
            python3 -m venv env
            . ./env/bin/activate
            pip install --no-input .
            pyinstaller -y pyavrocd.spec
            pip install --no-input patchelf-wrapper
            pip install --no-input staticx
            staticx dist/pyavrocd spyavrocd
            ./spyavrocd -V
            ./spyavrocd -d ? -t ?

      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: Linux32arm
          path: spyavrocd
