# build a arm-eabihf binary
name: Build PyAvrOCD on linux-armeabihf
on: [workflow_dispatch]

jobs:
  build-linux32-arm:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Qemu run
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: arm1176
          import_github_env: true
          copy_artifact_path: dist
          base_image: raspios_lite:latest
          image_additional_mb: 2048
          commands: |
            uname -a
            python3 --version
            ldd --version
            df -h /
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y git
            sudo apt install -y scons
            sudo apt install -y python3-pip
            sudo apt install -y python3.13-venv
            python3 -m venv env
            . ./env/bin/activate
            pip install --no-input .
            pyinstaller -y pyavrocd.spec
            ls -la .
            ls -la dist

      - name: Check file system
        run: |
          ls -la .
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm-linux-gnueabihf
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
