# Triggered by a new release, it will do a basic check on version number and unit tests.
# Then it will build the binaries and creates the binary release assets and the downloadable tools for Arduino
# Finally, it will upload the new version to PyPI
name: Release workflow

on:
  release:
    types: [published]
  workflow_dispatch: # to run it manually

jobs:
  check:
    defaults:
      run:
        shell: bash
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        if: ${{ github.event.release.tag_name != '' }}
        uses: actions/checkout@v5

      - name: Set up python
        if: ${{ github.event.release.tag_name != '' }}
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install dependencies

      - name: Test release against system version
        if: ${{ github.event.release.name != '' }}
        run: |
          VER=$(python pyavrocd/main.py -V)
          VERSTRING=v${VER#*version }
          VERSTRING=${VERSTRING%rc*}
          REL_NAME=${{ github.event.release.name }}
          echo "System version string: $VERSTRING"
          echo "Github release name: $REL_NAME"
          if [[ -z "$REL_NAME" ]]; then
             REL_NAME=$VERSTRING
             echo "Adapted GitHub release name to system version string"
          fi
          if [[ "$VERSTRING" != "$REL_NAME" ]]; then
             echo "Release version does not match system version"
             exit 1
          fi
          echo "Release and system version are identical, now we continue"

      - name: Check presence of correct i686 Linux version
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          I686_VER=$(extras/binaries/i686-linux-gnu/pyavrocd -V)
          I686_VERS=v${I686_VER#*version }
          I686_VERSTRING=${I686_VERS%rc*}
          REL_NAME=${{ github.event.release.name }}
          echo "i686 Linux system version string: $I686_VERSTRING"
          echo "Github release name: $REL_NAME"
          if [[ "$REL_NAME" != "$I686_VERSTRING" ]]; then
             echo "Wrong i686 version in repo!"
             exit 1
          fi
          echo "Release name and preloaded i686 binary have identical version numbers; we continue."

      - name: Run type checks linting and unit-tests
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          mypy .
          pylint pyavrocd
          pytest tests

  build-binaries:
    needs: check
    strategy:
      matrix:
       os: [ arm64-apple-darwin, aarch64-linux-gnu,  x86_64-mingw32,  x86_64-apple-darwin,  x86_64-linux-gnu, i686-mingw32]
       include:
         - os: arm64-apple-darwin
           runner: macos-14
           arch: arm64
         - os: aarch64-linux-gnu
           runner: ubuntu-24.04-arm
           arch: arm64
         - os: x86_64-mingw32
           runner: windows-2022
           arch: x64
         - os: x86_64-apple-darwin
           runner: macos-14-large
           arch: x64
         - os: x86_64-linux-gnu
           runner: ubuntu-24.04
           arch: x64
         - os: i686-mingw32
           runner: windows-2022
           arch: x86
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python

        uses: actions/setup-python@v6
        with:
          # for Linux use native Python so that staticx can work!
          if: ${{ !contains(matrix.os, 'linux') }}
          python-version: '3.14'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Install dependencies

      - name: Package PyAvrOCD with PyInstaller
        run: |
          pyinstaller -y pyavrocd.spec

      - name: Link statically and normalize for Linux binary
        if: ${{ contains(matrix.os, 'linux') }}
        run: |
          sudo apt-get install -y scons
          pip install patchelf-wrapper
          pip install staticx
          staticx dist/pyavrocd dist/pyavrocd-static
          rm dist/pyavrocd
          mkdir dist/pyavrocd
          mv dist/pyavrocd-static dist/pyavrocd/pyavrocd
          mkdir dist/pyavrocd/pyavrocd-util/
          cp -r svd dist/pyavrocd/pyavrocd-util/

      - name: Run pyavrocd
        run: |
          dist/pyavrocd/pyavrocd -V
          dist/pyavrocd/pyavrocd -d ? -t ?

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  build-armhf-binary:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Qemu run
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: arm1176
          import_github_env: true
          base_image: raspios_lite:latest
          copy_artifact_path: spyavrocd
          image_additional_mb: 2048
          commands: |
            uname -a
            python3 --version
            ldd --version
            df -h /
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y git
            sudo apt install -y scons
            sudo apt install -y python3-pip
            sudo apt install -y python3.13-venv
            python3 -m venv env
            . ./env/bin/activate
            pip install --no-input .
            pyinstaller -y pyavrocd.spec
            pip install --no-input patchelf-wrapper
            pip install --no-input staticx
            staticx dist/pyavrocd spyavrocd
            ./spyavrocd -V
            ./spyavrocd -d ? -t ?

      - name: Normalize file structure
        run: |
          rm -rf dist
          mkdir -p dist/pyavrocd/pyavrocd-util/svd
          cp svd/*.svd dist/pyavrocd/pyavrocd-util/svd/
          mv spyavrocd dist/pyavrocd/pyavrocd

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: arm-linux-gnueabihf
          path: dist/pyavrocd/*
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  build-assets:
    needs: [build-binaries, build-armhf-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download arm-linux-gnueabihf
        uses: actions/download-artifact@v7
        with:
          name: arm-linux-gnueabihf
          path: extras/binaries/arm-linux-gnueabihf

      - name: Download arm64-apple-darwin
        uses: actions/download-artifact@v7
        with:
          name: arm64-apple-darwin
          path: extras/binaries/arm64-apple-darwin

      - name: Download aarch64-linux-gnu
        uses: actions/download-artifact@v7
        with:
          name: aarch64-linux-gnu
          path: extras/binaries/aarch64-linux-gnu

      - name: Download x86_64-mingw32
        uses: actions/download-artifact@v7
        with:
          name: x86_64-mingw32
          path: extras/binaries/x86_64-mingw32

      - name: Download i686-mingw32
        uses: actions/download-artifact@v7
        with:
          name: i686-mingw32
          path: extras/binaries/i686-mingw32

      - name: Download x86_64-apple-darwin
        uses: actions/download-artifact@v7
        with:
          name: x86_64-apple-darwin
          path: extras/binaries/x86_64-apple-darwin

      - name: Download x86_64-linux-gnu
        uses: actions/download-artifact@v7
        with:
          name: x86_64-linux-gnu
          path: extras/binaries/x86_64-linux-gnu

      - name: Packing
        run: bash extras/packer.sh

      - name: Asset upload
        uses: softprops/action-gh-release@v3
        with:
          files: extras/assets/*.tar.gz

  build-pypi-distribution:
    name: Build distribution
    needs: build-assets
    runs-on: ubuntu-latest

    steps:
    - name: check for tag
      if: ${{ github.event.release.tag_name == '' }}
      run: exit 1

    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v6
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    if: ${{ !contains(github.event.release.name,'a') && !contains(github.event.release.name,'b') && github.event.release.name != '' }}
    needs:
    - build-pypi-distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/PyAvrOCD  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v7
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
